#include <algorithm>
#include <chrono>
#include <cstdint>
#include <fstream>
#include <functional>
#include <iostream>
#include <numeric>
#include <sstream>
#include <string>
#include <tuple>
#include <vector>

struct GridResult {
    std::vector<uint8_t> safe;
    uint64_t candidates = 0;
    uint64_t safe_count = 0;
};

static uint64_t rho_literal(uint64_t x, uint64_t M) {
    const uint64_t y = x % M;
    return std::min(y, M - y);
}

static GridResult literal_grid(const std::vector<uint64_t>& speeds,
                               uint64_t N,
                               uint64_t P) {
    const uint64_t M = N * P;
    GridResult out;
    out.safe.assign(static_cast<size_t>(M), 0);
    for (uint64_t r = 0; r < M; ++r) {
        if (r % N == 0) continue;
        ++out.candidates;
        bool ok = true;
        for (uint64_t s : speeds) {
            const uint64_t d = rho_literal(r * s, M);
            if (d < P) {
                ok = false;
                break;
            }
        }
        if (ok) {
            out.safe[static_cast<size_t>(r)] = 1;
            ++out.safe_count;
        }
    }
    return out;
}

// Independently structured implementation: initialize the canonical grid,
// then delete strict-bad residues for one speed at a time. Residues r*s mod M
// are generated by modular recurrence, not by product/remainder calls.
static GridResult recurrence_bad_union_grid(const std::vector<uint64_t>& speeds,
                                            uint64_t N,
                                            uint64_t P) {
    const uint64_t M = N * P;
    GridResult out;
    out.safe.assign(static_cast<size_t>(M), 0);
    for (uint64_t r = 0; r < M; ++r) {
        if (r % N != 0) {
            out.safe[static_cast<size_t>(r)] = 1;
            ++out.candidates;
        }
    }
    for (uint64_t s : speeds) {
        const uint64_t step = s % M;
        uint64_t y = 0;
        for (uint64_t r = 0; r < M; ++r) {
            if (out.safe[static_cast<size_t>(r)] != 0) {
                // rho_M(y) < P iff y < P or y > M-P. Equality is safe.
                if (y < P || y > M - P) {
                    out.safe[static_cast<size_t>(r)] = 0;
                }
            }
            y += step;
            if (y >= M) y -= M;
        }
    }
    for (uint8_t x : out.safe) out.safe_count += (x != 0);
    return out;
}

static bool top_two(const std::vector<uint64_t>& speeds, size_t jA, size_t jB) {
    if (jA == jB) return false;
    const uint64_t A = speeds[jA];
    const uint64_t B = speeds[jB];
    if (!(A < B)) return false;
    for (size_t i = 0; i < speeds.size(); ++i) {
        if (i != jB && speeds[i] > A) return false;
    }
    return true;
}

static uint64_t tuple_gcd(const std::vector<uint64_t>& v) {
    uint64_t g = 0;
    for (uint64_t x : v) g = std::gcd(g, x);
    return g;
}

static void emit_counterexample(std::ostream& os,
                                const std::vector<uint64_t>& speeds,
                                uint64_t N,
                                uint64_t A,
                                uint64_t B) {
    os << "COUNTEREXAMPLE\n";
    os << "n=" << speeds.size() << " N=" << N << " A=" << A << " B=" << B << "\n";
    os << "speeds=";
    for (size_t i = 0; i < speeds.size(); ++i) {
        if (i) os << ',';
        os << speeds[i];
    }
    os << "\n";
    os << "jA=" << speeds.size() - 2 << " jB=" << speeds.size() - 1 << "\n";
    os << "ratio_check=" << N*A << "<" << 2*B << "\n";
    for (const auto& [label, P] : std::vector<std::pair<std::string,uint64_t>>{{"A",A},{"B",B}}) {
        const uint64_t M = N * P;
        os << "grid_" << label << "_M=" << M << "\n";
        for (uint64_t r = 0; r < M; ++r) {
            if (r % N == 0) continue;
            bool found = false;
            for (size_t i = 0; i < speeds.size(); ++i) {
                const uint64_t d = rho_literal(r * speeds[i], M);
                if (d < P) {
                    os << "r=" << r << " spoiler_i=" << i
                       << " speed=" << speeds[i] << " rho=" << d << "<" << P << "\n";
                    found = true;
                    break;
                }
            }
            if (!found) os << "INTERNAL_ERROR_SAFE_R=" << r << "\n";
        }
    }
}

int main() {
    constexpr int N_MIN_DIM = 2;
    constexpr int N_MAX_DIM = 8;
    constexpr uint64_t B_MAX = 64;

    const auto started = std::chrono::steady_clock::now();
    uint64_t primitive_rows = 0;
    uint64_t nonprimitive_skipped = 0;
    uint64_t literal_candidates = 0;
    uint64_t optimized_candidates = 0;
    uint64_t placement_checks = 0;
    uint64_t mask_agreements = 0;
    uint64_t cert_A_rows = 0;
    uint64_t cert_B_rows = 0;
    uint64_t cert_both_rows = 0;

    std::ostringstream report;
    report << "program=p64_top_two_sweep_v1\n";
    report << "domain=n:2..8; B<=64; positive strictly increasing tuples; gcd=1; (n+1)A<2B\n";
    report << "order=n ascending, B ascending, A ascending, lower tuple lexicographic\n";
    report << "compiler_standard=c++20\n";

    bool found_counterexample = false;

    for (int n = N_MIN_DIM; n <= N_MAX_DIM && !found_counterexample; ++n) {
        const uint64_t N = static_cast<uint64_t>(n + 1);
        const int lower_count = n - 2;
        for (uint64_t B = 1; B <= B_MAX && !found_counterexample; ++B) {
            for (uint64_t A = 1; A < B && !found_counterexample; ++A) {
                if (!(N * A < 2 * B)) continue;
                if (A < static_cast<uint64_t>(lower_count + 1)) continue;

                std::vector<uint64_t> lower(static_cast<size_t>(lower_count));
                std::function<void(int,uint64_t)> rec;
                rec = [&](int pos, uint64_t next) {
                    if (found_counterexample) return;
                    if (pos == lower_count) {
                        std::vector<uint64_t> speeds = lower;
                        speeds.push_back(A);
                        speeds.push_back(B);
                        if (tuple_gcd(speeds) != 1) {
                            ++nonprimitive_skipped;
                            return;
                        }
                        ++primitive_rows;

                        // Explicitly audit every possible placement of the two top indices.
                        // Lower speeds retain increasing order in the remaining slots.
                        for (size_t jA = 0; jA < speeds.size(); ++jA) {
                            for (size_t jB = 0; jB < speeds.size(); ++jB) {
                                if (jA == jB) continue;
                                std::vector<uint64_t> indexed(speeds.size(), 0);
                                indexed[jA] = A;
                                indexed[jB] = B;
                                size_t k = 0;
                                for (size_t i = 0; i < indexed.size(); ++i) {
                                    if (i == jA || i == jB) continue;
                                    indexed[i] = lower[k++];
                                }
                                if (!top_two(indexed, jA, jB)) {
                                    report << "TOP_TWO_PLACEMENT_FAILURE row=" << primitive_rows
                                           << " jA=" << jA << " jB=" << jB << "\n";
                                    found_counterexample = true; // internal fatal marker
                                    return;
                                }
                                ++placement_checks;
                            }
                        }

                        const auto LA = literal_grid(speeds, N, A);
                        const auto OA = recurrence_bad_union_grid(speeds, N, A);
                        const auto LB = literal_grid(speeds, N, B);
                        const auto OB = recurrence_bad_union_grid(speeds, N, B);
                        literal_candidates += LA.candidates + LB.candidates;
                        optimized_candidates += OA.candidates + OB.candidates;

                        if (LA.candidates != OA.candidates || LB.candidates != OB.candidates ||
                            LA.safe != OA.safe || LB.safe != OB.safe) {
                            report << "IMPLEMENTATION_DISAGREEMENT row=" << primitive_rows << "\n";
                            found_counterexample = true; // internal fatal marker
                            return;
                        }
                        mask_agreements += 2;

                        const bool certA = LA.safe_count != 0;
                        const bool certB = LB.safe_count != 0;
                        cert_A_rows += certA;
                        cert_B_rows += certB;
                        cert_both_rows += (certA && certB);
                        if (!certA && !certB) {
                            emit_counterexample(report, speeds, N, A, B);
                            found_counterexample = true;
                            return;
                        }
                        return;
                    }
                    const uint64_t need_after = static_cast<uint64_t>(lower_count - pos - 1);
                    if (next + need_after >= A) return;
                    for (uint64_t x = next; x < A; ++x) {
                        if (x + need_after >= A) break;
                        lower[static_cast<size_t>(pos)] = x;
                        rec(pos + 1, x + 1);
                        if (found_counterexample) return;
                    }
                };
                rec(0, 1);
            }
        }
    }

    const auto stopped = std::chrono::steady_clock::now();
    const double seconds = std::chrono::duration<double>(stopped - started).count();
    report << "primitive_rows=" << primitive_rows << "\n";
    report << "nonprimitive_skipped=" << nonprimitive_skipped << "\n";
    report << "literal_candidates=" << literal_candidates << "\n";
    report << "optimized_candidates=" << optimized_candidates << "\n";
    report << "placement_checks=" << placement_checks << "\n";
    report << "mask_agreements=" << mask_agreements << "\n";
    report << "cert_A_rows=" << cert_A_rows << "\n";
    report << "cert_B_rows=" << cert_B_rows << "\n";
    report << "cert_both_rows=" << cert_both_rows << "\n";
    report << "counterexample_found=" << (found_counterexample ? 1 : 0) << "\n";
    report << "runtime_seconds=" << seconds << "\n";

    std::cout << report.str();
    return found_counterexample ? 2 : 0;
}
