import LonelyRunner

/-!
Run with `lake env lean LonelyRunner/AxiomAudit.lean`.

These commands report the axioms used by the statement-equivalence layer.  The
expected output is only Lean's standard logical foundations (typically
propositional extensionality and quotient soundness where applicable), never a
project-specific axiom.
-/

#print axioms LonelyRunner.lonelyAt_iff_relativeLonelyAt
#print axioms LonelyRunner.conjecture_iff_nonnegativeTimeConjecture
#print axioms LonelyRunner.conjecture_iff_relativeConjecture
#print axioms LonelyRunner.conjecture_iff_distinctStationaryConjecture
#print axioms LonelyRunner.distinctStationaryConjecture_iff_stationaryConjecture
#print axioms LonelyRunner.conjecture_iff_stationaryConjecture
#print axioms LonelyRunner.oneMovingRunner
#print axioms LonelyRunner.StationaryConjecture
#print axioms LonelyRunner.DistinctStationaryConjecture
#print axioms LonelyRunner.PositiveIntegerConjecture
#print axioms LonelyRunner.abs_circleNorm_sub_circleNorm_le
#print axioms LonelyRunner.exists_small_shift_circleNorm_ge
#print axioms LonelyRunner.fastRunnerInsertion
#print axioms LonelyRunner.exists_int_grid_circleNorm_ge
#print axioms LonelyRunner.exists_int_coprime_grid_circleNorm_ge
#print axioms LonelyRunner.codimensionOneDivisorInsertion
#print axioms LonelyRunner.circleNorm_ge_of_int_band
#print axioms LonelyRunner.minimumScaleResidueBands
#print axioms LonelyRunner.card_biUnion_le_sum_card
#print axioms LonelyRunner.exists_mem_avoiding_of_sum_card_lt_card
#print axioms LonelyRunner.card_union_le_card_add_selected_remainder
#print axioms LonelyRunner.card_ordered_union_le_sum_selected_remainders
#print axioms LonelyRunner.exists_mem_avoiding_ordered_of_sum_lt_card
#print axioms LonelyRunner.card_pivotCandidates
#print axioms LonelyRunner.circleNorm_nat_div_ge
#print axioms LonelyRunner.circleNorm_nat_div_eq
#print axioms LonelyRunner.not_mem_pivotBadResidues_iff_circleNorm_ge
#print axioms LonelyRunner.pivotResidueWitness
#print axioms LonelyRunner.card_strictCyclicBall
#print axioms LonelyRunner.card_mul_mod_strictCyclicBall
#print axioms LonelyRunner.card_pivotBadResidues_exact
#print axioms LonelyRunner.exists_boundary_witness
#print axioms LonelyRunner.exists_safe_pivot_residue
#print axioms LonelyRunner.exists_witness_iff_exists_pivot_certificate
#print axioms LonelyRunner.positiveIntegerConjecture_iff_pivotCertificateConjecture
#print axioms LonelyRunner.divisorInsertionCase_of_coprime_commonDivisor_two_le
#print axioms LonelyRunner.exists_appended_witness_of_integerInsertionCover
#print axioms LonelyRunner.positiveIntegerConjecture_iff_divisorOrUncoveredPivotPrinciple
#print axioms LonelyRunner.capacitatedHall_iff_existsInjective
#print axioms LonelyRunner.card_orderedFinsetUnion_add_orderedOverlapCredit
#print axioms LonelyRunner.pairSumCertificate_iff_pair_time
#print axioms LonelyRunner.positiveIntegerPairSumCertificateConjecture_imp_positiveIntegerConjecture
#print axioms LonelyRunner.circleNorm_mul_abs_right
#print axioms LonelyRunner.exists_stationaryWitness_abs_iff
#print axioms LonelyRunner.exists_stationaryWitness_scale_iff
#print axioms LonelyRunner.exists_stationaryWitness_natScale_iff
#print axioms LonelyRunner.clearRationalSpeed_cast
#print axioms LonelyRunner.clearRationalSpeed_injective
#print axioms LonelyRunner.positiveIntegerConjecture_iff_distinctPositiveRationalConjecture
#print axioms LonelyRunner.distinctPositiveRationalConjecture_iff_positiveRationalConjecture
#print axioms LonelyRunner.positiveIntegerConjecture_iff_positiveRationalConjecture
#print axioms LonelyRunner.mFourier_orbitHom_eq_one_iff
#print axioms LonelyRunner.integrable_add_closedSubgroup
#print axioms LonelyRunner.continuous_integral_add_closedSubgroup
#print axioms LonelyRunner.integral_mFourier_closedSubgroup_eq_zero_of_exists_ne_one
#print axioms LonelyRunner.closedSubgroupCosetSeparator_eq_one
#print axioms LonelyRunner.exists_mFourier_separating
#print axioms LonelyRunner.orbitHom_mem_orbitTopologicalClosure_of_relations
#print axioms LonelyRunner.orbitHom_mem_closure_range_of_relations
#print axioms LonelyRunner.velocity_reconstruction
#print axioms LonelyRunner.integer_relation_annihilates_row
#print axioms LonelyRunner.bhk_adjacentRatioCombination
#print axioms LonelyRunner.exists_adjacent_image_values
#print axioms LonelyRunner.bhk_collisionWitness_of_adjacentRatios
#print axioms LonelyRunner.exists_positive_rational_of_integer_relations
#print axioms LonelyRunner.exists_rationalRow_ratio_ne_of_irrational
#print axioms LonelyRunner.exists_bhk_collisionWitness_of_irrational
#print axioms LonelyRunner.exists_stationaryWitness_of_rational_collision
#print axioms LonelyRunner.positiveRationalConjecture_implies_positiveRealWitness
#print axioms LonelyRunner.positiveRationalConjecture_implies_stationaryConjecture
#print axioms LonelyRunner.stationaryConjecture_iff_positiveRationalConjecture
#print axioms LonelyRunner.conjecture_iff_positiveIntegerConjecture
#print axioms LonelyRunner.twoMovingSpeeds_of_abs_le
#print axioms LonelyRunner.twoMovingSpeeds
#print axioms LonelyRunner.twoMovingRunners
