import LonelyRunner
import LonelyRunner.FastestPivot
import LonelyRunner.TopTwoTransversal
import LonelyRunner.FourRunnerOrdinary
import LonelyRunner.BoundedRealReduction
import LonelyRunner.FourRunnerCanonical
import LonelyRunner.BufferedRunnerInsertion
import LonelyRunner.FiveRunnerMixed
import LonelyRunner.FiveRunnerBuffered
import LonelyRunner.RationalMarginCertificates
import LonelyRunner.EndpointCompleteness
import LonelyRunner.StrictPairSumCompleteness

-- The exact finite-family equivalence does not prove either side.
#print axioms LonelyRunner.exists_strictMono_reindex
#print axioms LonelyRunner.lonelyAt_reindex_translate_scale_iff
#print axioms LonelyRunner.exists_sorted_primitive_integer_normalization
#print axioms LonelyRunner.InclusivePrimitiveFiniteFamily
#print axioms LonelyRunner.AllInclusivePrimitiveFiniteFamilies
#print axioms LonelyRunner.integer_lonelyAt_of_lower_and_finiteFamily
#print axioms LonelyRunner.PositiveIntegerAtCount
#print axioms LonelyRunner.lowerCount_of_previous_counts
#print axioms LonelyRunner.positiveIntegerAtCount_of_lower_and_finiteFamily
#print axioms LonelyRunner.positiveIntegerConjecture_of_allInclusivePrimitiveFiniteFamilies
#print axioms LonelyRunner.conjecture_iff_allInclusivePrimitiveFiniteFamilies

-- Conditional affine supply keeps the smaller-count premise explicit.
#print axioms LonelyRunner.LowerCountPositiveIntegerHypothesis
#print axioms LonelyRunner.lowerCountPositiveIntegerHypothesis_rational
#print axioms LonelyRunner.exists_lowerCount_rational_collision
#print axioms LonelyRunner.exists_bhk_twoPhase_margin
#print axioms LonelyRunner.exists_normalized_affine_second_phase
#print axioms LonelyRunner.exists_affinePhaseTransfer
#print axioms LonelyRunner.exists_positiveAffine_witness
#print axioms LonelyRunner.exists_signedAffine_witness
#print axioms LonelyRunner.fractionalBox
#print axioms LonelyRunner.fractionalBox_eq_error
#print axioms LonelyRunner.exists_simultaneous_integer_approximation
#print axioms LonelyRunner.RationalPairRankTwo
#print axioms LonelyRunner.rationalPairRankTwo_elim
#print axioms LonelyRunner.relative_ratio_nonconstant_of_rankTwo
#print axioms LonelyRunner.exists_endpoint_affine_approximation
#print axioms LonelyRunner.primitive_dvd_of_scaled_dvd
#print axioms LonelyRunner.rankTwo_of_primitive_approximation
#print axioms LonelyRunner.rational_affine_lonelyAt
#print axioms LonelyRunner.primitive_sorted_largeHeight_lonelyAt
#print axioms LonelyRunner.exists_affinePhaseTransfer_with_zeroResidual
#print axioms LonelyRunner.exists_positiveAffine_witness_with_zeroResidual
#print axioms LonelyRunner.exists_signedAffine_witness_with_zeroResidual
#print axioms LonelyRunner.rational_affine_lonelyAt_with_equalResidual
#print axioms LonelyRunner.primitive_sorted_largeHeight_stationary_mixed
#print axioms LonelyRunner.primitive_sorted_noMixed_height_le

-- Unequal clusters retain their actual count through the canonical bridge.
#print axioms LonelyRunner.twoClusterPhaseBand
#print axioms LonelyRunner.twoClusterPhaseSupply
#print axioms LonelyRunner.twoClusterPhaseCellWitness
#print axioms LonelyRunner.twoClusterSpeeds
#print axioms LonelyRunner.card_twoClusterSpeeds
#print axioms LonelyRunner.twoClusterSpeeds_member_le
#print axioms LonelyRunner.twoClusterSpeeds_reflect_mem
#print axioms LonelyRunner.mem_twoClusterSpeeds_reflect_iff
#print axioms LonelyRunner.twoClusterLowerRunner
#print axioms LonelyRunner.twoClusterRunnerWitness
#print axioms LonelyRunner.twoClusterLonelyAt

-- The mirrored family has an unconditional witness and an exact labelled bridge.
#print axioms LonelyRunner.mirroredBlockTime
#print axioms LonelyRunner.mirroredConsecutiveBlockWitness
#print axioms LonelyRunner.mirroredBlockSpeeds
#print axioms LonelyRunner.card_mirroredBlockSpeeds
#print axioms LonelyRunner.mirroredBlockMagnitudeCover
#print axioms LonelyRunner.mirroredBlockLowerRunner
#print axioms LonelyRunner.mirroredBlockRunnerWitness
#print axioms LonelyRunner.mirroredBlockLonelyAt

/-!
Run with `lake env lean LonelyRunner/AxiomAudit.lean`.

These commands report the axioms used by the statement-equivalence layer.  The
expected output is only Lean's standard logical foundations (typically
propositional extensionality and quotient soundness where applicable), never a
project-specific axiom.
-/

#print axioms LonelyRunner.lonelyAt_iff_relativeLonelyAt
#print axioms LonelyRunner.conjecture_iff_nonnegativeTimeConjecture
#print axioms LonelyRunner.conjecture_iff_relativeConjecture
#print axioms LonelyRunner.conjecture_iff_distinctStationaryConjecture
#print axioms LonelyRunner.distinctStationaryConjecture_iff_stationaryConjecture
#print axioms LonelyRunner.conjecture_iff_stationaryConjecture
#print axioms LonelyRunner.oneMovingRunner
#print axioms LonelyRunner.StationaryConjecture
#print axioms LonelyRunner.DistinctStationaryConjecture
#print axioms LonelyRunner.PositiveIntegerConjecture
#print axioms LonelyRunner.abs_circleNorm_sub_circleNorm_le
#print axioms LonelyRunner.exists_small_shift_circleNorm_ge
#print axioms LonelyRunner.fastRunnerInsertion
#print axioms LonelyRunner.exists_int_grid_circleNorm_ge
#print axioms LonelyRunner.exists_int_coprime_grid_circleNorm_ge
#print axioms LonelyRunner.codimensionOneDivisorInsertion
#print axioms LonelyRunner.circleNorm_ge_of_int_band
#print axioms LonelyRunner.minimumScaleResidueBands
#print axioms LonelyRunner.card_biUnion_le_sum_card
#print axioms LonelyRunner.exists_mem_avoiding_of_sum_card_lt_card
#print axioms LonelyRunner.card_union_le_card_add_selected_remainder
#print axioms LonelyRunner.card_ordered_union_le_sum_selected_remainders
#print axioms LonelyRunner.exists_mem_avoiding_ordered_of_sum_lt_card
#print axioms LonelyRunner.card_pivotCandidates
#print axioms LonelyRunner.circleNorm_nat_div_ge
#print axioms LonelyRunner.circleNorm_nat_div_eq
#print axioms LonelyRunner.not_mem_pivotBadResidues_iff_circleNorm_ge
#print axioms LonelyRunner.pivotResidueWitness
#print axioms LonelyRunner.reverseGrid_exact_identity
#print axioms LonelyRunner.reverseGrid_deficit_pos
#print axioms LonelyRunner.reverseGrid_residue_lt
#print axioms LonelyRunner.reverseGrid_residue_modEq
#print axioms LonelyRunner.reverseGrid_phase_mod_one
#print axioms LonelyRunner.signedCyclicResidueDistance_ofNat
#print axioms LonelyRunner.signedCyclicResidueDistance_congr
#print axioms LonelyRunner.signedCyclicResidueDistance_neg
#print axioms LonelyRunner.reverseGrid_deleted_boundary
#print axioms LonelyRunner.reverseGrid_pivot_modEq
#print axioms LonelyRunner.reverseGrid_pivot_distance
#print axioms LonelyRunner.exists_fastestPivotCertificate_of_ratio
#print axioms LonelyRunner.fastestPivot_family_witness
#print axioms LonelyRunner.slowest_fastest_gap_of_no_fastestPivotCertificate
#print axioms LonelyRunner.pivot_le_cyclicResidueDistance_mul_of_band
#print axioms LonelyRunner.exists_fastestPivotCertificate_of_extremal_band
#print axioms LonelyRunner.exists_fastestPivotCertificate_of_mem_extremal_interval
#print axioms LonelyRunner.extremal_interval_compression_of_no_fastestPivotCertificate
#print axioms LonelyRunner.isTwoSidedTransversal_of_covers
#print axioms LonelyRunner.exists_top_certificate_of_not_isTwoSidedTransversal
#print axioms LonelyRunner.saturatedTopTwoPivotCertificate
#print axioms LonelyRunner.saturatedTopTwo_avoids_pivotBadResidues
#print axioms LonelyRunner.card_strictCyclicBall
#print axioms LonelyRunner.card_mul_mod_strictCyclicBall
#print axioms LonelyRunner.card_pivotBadResidues_exact
#print axioms LonelyRunner.normalizedBadCount
#print axioms LonelyRunner.card_pivotBadResidues_normalized
#print axioms LonelyRunner.commonPivotBadCount_eq_card
#print axioms LonelyRunner.exists_commonPivotCandidate_of_sum_badCount_lt
#print axioms LonelyRunner.commonPivotCandidate_avoids_unitMultiple
#print axioms LonelyRunner.scaledCommonPivotTime_eq
#print axioms LonelyRunner.simultaneousTopTwo_of_commonPivotBadCount
#print axioms LonelyRunner.mem_rectangleC0_union_C1_of_generic
#print axioms LonelyRunner.rectangleD0_disjoint_D1
#print axioms LonelyRunner.rectangleD0_subset_extra
#print axioms LonelyRunner.rectangleD1_subset_extra
#print axioms LonelyRunner.rectangleC0_D1_band
#print axioms LonelyRunner.rectangleC1_D0_band
#print axioms LonelyRunner.rectangle_coprime_injections_give_sdr
#print axioms LonelyRunner.rectangleReversal_C0_mem_D1
#print axioms LonelyRunner.rectangleReversal_C1_mem_D0
#print axioms LonelyRunner.coprime_rectangleReversal
#print axioms LonelyRunner.rectangleReversal_gives_sdr
#print axioms LonelyRunner.rectangleStartFeasible_iff
#print axioms LonelyRunner.rectangleReversalAt_isSdr_of_feasible
#print axioms LonelyRunner.rectangleReversalAt_isSdr_of_mem_startInterval
#print axioms LonelyRunner.gammaTwoTranslation_isSdr

#print axioms LonelyRunner.PartialMatching.extension_or_deficiency_one
#print axioms LonelyRunner.tight_iff_successorClosed_and_avoidsBad
#print axioms LonelyRunner.strictHall_iff_every_vertex_reaches_bad
#print axioms LonelyRunner.nonReachingSet_tight
#print axioms LonelyRunner.residual_every_vertex_reaches_bad
#print axioms LonelyRunner.residual_strictHall
#print axioms LonelyRunner.criticalCore_coSingleton_tight
#print axioms LonelyRunner.atomicCriticalCore_card_eq_one
#print axioms LonelyRunner.simultaneousCongruenceCompatible_iff_nonempty
#print axioms LonelyRunner.card_simultaneousCongruenceResidues
#print axioms LonelyRunner.tripleCongruenceCompatible_iff_nonempty
#print axioms LonelyRunner.card_tripleCongruenceResidues
#print axioms LonelyRunner.card_tripleCongruenceResidues_zero_coefficients
#print axioms LonelyRunner.biUnion_pivotTargetFiber_eq_pivotBadResidues
#print axioms LonelyRunner.card_simultaneousCongruenceNatResidues_exact
#print axioms LonelyRunner.divisibleSimultaneousCongruenceNatResidues_eq_image
#print axioms LonelyRunner.card_divisibleSimultaneousCongruenceNatResidues_if
#print axioms LonelyRunner.candidateSimultaneousCongruenceCount_exact
#print axioms LonelyRunner.card_pivotTargetFiber_inter_pivotBadResidues
#print axioms LonelyRunner.card_pivotTargetFiber_inter_pivotBadResidues_eq_sum_raw_sub_if
#print axioms LonelyRunner.card_pivotTargetFiber_inter_pivotBadResidues_exact
#print axioms LonelyRunner.card_tripleCongruenceNatResidues_exact
#print axioms LonelyRunner.divisibleTripleCongruenceNatResidues_eq_image
#print axioms LonelyRunner.card_divisibleTripleCongruenceNatResidues_if
#print axioms LonelyRunner.candidateTripleCongruenceCount_exact
#print axioms LonelyRunner.candidateTripleCongruenceCount_exact_of_mem_strictCyclicBall
#print axioms LonelyRunner.exists_boundary_witness
#print axioms LonelyRunner.exists_safe_pivot_residue
#print axioms LonelyRunner.exists_witness_iff_exists_pivot_certificate
#print axioms LonelyRunner.positiveIntegerConjecture_iff_pivotCertificateConjecture
#print axioms LonelyRunner.divisorInsertionCase_of_coprime_commonDivisor_two_le
#print axioms LonelyRunner.exists_appended_witness_of_integerInsertionCover
#print axioms LonelyRunner.positiveIntegerConjecture_iff_divisorOrUncoveredPivotPrinciple
#print axioms LonelyRunner.capacitatedHall_iff_existsInjective
#print axioms LonelyRunner.card_orderedFinsetUnion_add_orderedOverlapCredit
#print axioms LonelyRunner.fiberCredit_le_card_inter_biUnion
#print axioms LonelyRunner.exists_mem_avoiding_of_balanced_fiberCredit
#print axioms LonelyRunner.fiberCredit_le_twoLevelFiberCredit_le_card_inter_biUnion
#print axioms LonelyRunner.exists_mem_avoiding_of_twoLevelFiberCredit_sum_lt_card_of_parent_subset
#print axioms LonelyRunner.exists_mem_avoiding_of_twoLevelFiberCredit_sum_lt_card
#print axioms LonelyRunner.subfiber_anchor_add_sup_eq_if_of_saturated
#print axioms LonelyRunner.average_rankedTailCredit
#print axioms LonelyRunner.exists_code_cost_lt_of_rankedTailAverage
#print axioms LonelyRunner.exists_nextPotential_le_of_eq_weightedAverage
#print axioms LonelyRunner.exists_removalOrder_terminalPotential_le
#print axioms LonelyRunner.orderedDistinctPairSum_left
#print axioms LonelyRunner.exists_threeDistinctAnchors_of_anchorStar_gt
#print axioms LonelyRunner.exists_threeDistinctAnchors_of_anchorStar_gt_of_card
#print axioms LonelyRunner.subfiber_pair_anchor_credit_eq_card_inter_union
#print axioms LonelyRunner.directionalGains_add_reverse_eq_natPairwiseDispersion
#print axioms LonelyRunner.orderedDistinctPairAverage_mono_of_nat
#print axioms LonelyRunner.exists_orderCredit_ge_iff_exists_acyclicSelectorWeight_ge
#print axioms LonelyRunner.orderCredit_le_iff_acyclicSelectorWeight_le
#print axioms LonelyRunner.orderCredit_modular_eq_fiberCredit_sum
#print axioms LonelyRunner.exists_modularOrderFiberCredit_ge_iff_exists_acyclicSelectorWeight_ge
#print axioms LonelyRunner.sum_card_sub_modularOrderFiberCredit_eq_sum_child_net
#print axioms LonelyRunner.exists_pivotCandidate_avoiding_of_modularOrderFiberCredit
#print axioms LonelyRunner.exists_real_witness_of_modularOrderFiberCredit
#print axioms LonelyRunner.orderPotential_eq_orderCredit_add_orderSoftLoss
#print axioms LonelyRunner.exists_peelingList_of_localBudget
#print axioms LonelyRunner.exists_criticalCore_of_budget_lt_every_peeling
#print axioms LonelyRunner.exists_criticalSoftCore_of_budget_lt_every_peeling
#print axioms LonelyRunner.exists_blockPeelingList_of_localBudget
#print axioms LonelyRunner.exists_blockPeelingList_of_strictLocalBudget
#print axioms LonelyRunner.blockPeelingBudget_oneStepBlockBudget
#print axioms LonelyRunner.exists_blockPeelingList_of_localVertexBudget
#print axioms LonelyRunner.bellmanPotential_le_peelingLoss_of_complete
#print axioms LonelyRunner.bellmanPotential_univ_le_peelingLoss
#print axioms LonelyRunner.optimalPeelingPotential_characterization
#print axioms LonelyRunner.bellmanPotential_le_optimalPeelingPotential
#print axioms LonelyRunner.overlapPointUse_le_capacity_of_injectiveOwner_of_unowned
#print axioms LonelyRunner.overlapPointUse_le_capacity_of_ordered_injectiveOwner
#print axioms LonelyRunner.card_biUnion_add_sum_card_blocks_le_sum_card_bad
#print axioms LonelyRunner.exists_avoiding_of_overlapCapacity
#print axioms LonelyRunner.card_biUnion_le_sum_card_bad_sub_sum_card_blocks
#print axioms LonelyRunner.exists_pivot_certificate_of_overlapPacking
#print axioms LonelyRunner.alternatingChoosePrefix_succ
#print axioms LonelyRunner.correlationPolynomial_cleared_eq
#print axioms LonelyRunner.correlationPolynomial_cleared_nonpos
#print axioms LonelyRunner.correlationPolynomial_zero
#print axioms LonelyRunner.correlationPolynomial_le_zeroIndicator
#print axioms LonelyRunner.sum_card_zeroCandidateSlice_eq_weighted_zero_count
#print axioms LonelyRunner.cast_sum_card_zeroCandidateSlice_eq_weightedZeroIndicatorSum
#print axioms LonelyRunner.weightedStatisticSum_le_weightedZeroIndicatorSum
#print axioms LonelyRunner.weightedCandidateStatisticSum_le_cast_sum_card_zeroCandidateSlice
#print axioms LonelyRunner.weighted_hockey_stick
#print axioms LonelyRunner.consecutive_extreme_debt_sum
#print axioms LonelyRunner.clearedCorrelationHistogram_le
#print axioms LonelyRunner.clearedCorrelationHistogram_le_of_zeroMass
#print axioms LonelyRunner.momentHistogramScore_pos
#print axioms LonelyRunner.rationalChebyshevValue_bounds
#print axioms LonelyRunner.chebyshevMomentGrid_boundedZeroTest
#print axioms LonelyRunner.chebyshevMomentHistogramScore_pos
#print axioms LonelyRunner.smallDenominator_stationary_witness
#print axioms LonelyRunner.divisor_cover_of_no_small_witness
#print axioms LonelyRunner.exists_modEq_one_in_interval
#print axioms LonelyRunner.coprime_add_of_mod_eq_one
#print axioms LonelyRunner.exists_inverseRepresentative
#print axioms LonelyRunner.two_le_cyclicResidueDistance_of_inverse_avoids_two_holes
#print axioms LonelyRunner.twoHoleDenominator_family_witness
#print axioms LonelyRunner.boundedHeight_family_witness_of_two_holes
#print axioms LonelyRunner.boundedHeight_stationary_witness
#print axioms LonelyRunner.cardDistinctFactors_eq_primeFactors_card
#print axioms LonelyRunner.two_pow_cardDistinctFactors_le
#print axioms LonelyRunner.cardDistinctFactors_le_log_two
#print axioms LonelyRunner.prod_le_card_succ_mul_prod_pred
#print axioms LonelyRunner.le_cardDistinctFactors_succ_mul_totient
#print axioms LonelyRunner.le_log_succ_mul_totient
#print axioms LonelyRunner.exists_coprime_in_Ico_of_complement_lt_totient
#print axioms LonelyRunner.exists_coprime_in_Ico_full_period
#print axioms LonelyRunner.twoHole_witness_of_coprime_modulus_above_height
#print axioms LonelyRunner.logarithmicHeight_family_witness
#print axioms LonelyRunner.logarithmicHeight_stationary_witness
#print axioms LonelyRunner.logarithmicHeightGain_spec
#print axioms LonelyRunner.logarithmicHeightGain_stationary_witness
#print axioms LonelyRunner.logarithmicHeightGain_positiveInteger_witness
#print axioms LonelyRunner.rational_short_interval_bound
#print axioms LonelyRunner.rationalCoefficientHeight_family_witness
#print axioms LonelyRunner.rationalCoefficientHeightGain_spec
#print axioms LonelyRunner.rationalCoefficientHeightGain_maximal
#print axioms LonelyRunner.rationalCoefficientHeightGain_family_witness
#print axioms LonelyRunner.totient_primorial_eq_prod_primesLE_pred
#print axioms LonelyRunner.boundedPrimorial_pos
#print axioms LonelyRunner.boundedPrimorialPredProduct_pos
#print axioms LonelyRunner.boundedPrimorial_le
#print axioms LonelyRunner.primorial_le_boundedPrimorial
#print axioms LonelyRunner.boundedPrimorial_ratio_dominates
#print axioms LonelyRunner.boundedPrimorial_ratio_maximum
#print axioms LonelyRunner.boundedPrimorialCoefficient_pos
#print axioms LonelyRunner.boundedPrimorialHeightGain_spec
#print axioms LonelyRunner.boundedPrimorialHeightGain_maximal
#print axioms LonelyRunner.boundedPrimorialRatioHeight_family_witness
#print axioms LonelyRunner.boundedPrimorialHeight_family_witness
#print axioms LonelyRunner.boundedPrimorialHeight_stationary_witness
#print axioms LonelyRunner.boundedPrimorialHeightGain_family_witness_of_ratio
#print axioms LonelyRunner.boundedPrimorialHeightGain_family_witness
#print axioms LonelyRunner.cardDistinctFactors_one
#print axioms LonelyRunner.cardDistinctFactors_prime_pow
#print axioms LonelyRunner.cardDistinctFactors_six
#print axioms LonelyRunner.five_mul_two_pow_omega_le_two_mul
#print axioms LonelyRunner.small_modulus_power_le_interval
#print axioms LonelyRunner.small_modulus_power_le_interval_seventeen
#print axioms LonelyRunner.seventeenThirdsHeight_family_witness_of_kanold
#print axioms LonelyRunner.sixHeight_family_witness_of_kanold
#print axioms LonelyRunner.subsetExponent_mod_injective
#print axioms LonelyRunner.exponential_sum_not_vanish_consecutively
#print axioms LonelyRunner.primitiveRoot_subset_nodes_injective
#print axioms LonelyRunner.roots_product_expansion
#print axioms LonelyRunner.roots_product_eq_zero_of_dvd
#print axioms LonelyRunner.exists_avoiding_prime_set
#print axioms LonelyRunner.coprime_of_avoids_primeFactors
#print axioms LonelyRunner.kanoldIntervalBound_vandermonde
#print axioms LonelyRunner.seventeenThirdsHeight_family_witness
#print axioms LonelyRunner.sixHeight_family_witness
#print axioms LonelyRunner.three_mul_two_pow_omega_le
#print axioms LonelyRunner.five_short_interval_exception_classification
#print axioms LonelyRunner.five_witness_or_exception
#print axioms LonelyRunner.exists_second_missing_of_extra_speed
#print axioms LonelyRunner.fiveHeight_family_witness
#print axioms LonelyRunner.five_mul_two_pow_omega_le_of_40_le
#print axioms LonelyRunner.four_short_interval_exception_classification
#print axioms LonelyRunner.four_witness_or_exception
#print axioms LonelyRunner.fourHeight_family_witness
#print axioms LonelyRunner.three_short_interval_large_or_exception
#print axioms LonelyRunner.three_witness_or_large_or_exception
#print axioms LonelyRunner.threeHeight_family_witness
#print axioms LonelyRunner.DeletionPivotCertificate.exists_full_witness_of_exceptionalGood

#print axioms LonelyRunner.exists_full_witness_of_all_deletions_and_selector
#print axioms LonelyRunner.exists_full_witness_of_corrected_deletionPivotLiftingPrinciple
#print axioms LonelyRunner.mem_pivotBadResidues_mul_iff
#print axioms LonelyRunner.card_pivotSafeResidues_le_mul
#print axioms LonelyRunner.top_signed_forces_sum
#print axioms LonelyRunner.comparable_signedDivisor_necessary
#print axioms LonelyRunner.comparable_signedDivisor_sufficient
#print axioms LonelyRunner.comparable_signedDivisor_iff
#print axioms LonelyRunner.comparable_signedDivisor_sufficient_ordered
#print axioms LonelyRunner.replacement_sum_lt
#print axioms LonelyRunner.chain3Counterexample_directWitness
#print axioms LonelyRunner.optAddCounterexample_directWitness
#print axioms LonelyRunner.pairMultiplicityContribution_num
#print axioms LonelyRunner.sum_pairMultiplicityContribution_num
#print axioms LonelyRunner.residueEnergy_nat_add_mod_le
#print axioms LonelyRunner.residueEnergy_sum_mod_le
#print axioms LonelyRunner.rangeProfileDispersion_eq
#print axioms LonelyRunner.rangeSumProfileLowerBound_of_cutDecomposition
#print axioms LonelyRunner.rangeProfileDispersion_singleton
#print axioms LonelyRunner.fixedRow_pairDeficit_add_binary_eq_neg_debt
#print axioms LonelyRunner.sum_fixedRow_pairDeficit_add_binary_eq_neg_debt
#print axioms LonelyRunner.fixedRowDebtContributionNum_nonneg
#print axioms LonelyRunner.fixedRowCellLoss_nonneg
#print axioms LonelyRunner.fixedRow_debt_loss_decomposition
#print axioms LonelyRunner.sum_fixedRowCellLoss_nonneg
#print axioms LonelyRunner.exists_cost_lt_of_decreasing_move
#print axioms LonelyRunner.prefixDependentCost_relocate
#print axioms LonelyRunner.pairSumCertificate_iff_pair_time
#print axioms LonelyRunner.positiveIntegerPairSumCertificateConjecture_imp_positiveIntegerConjecture
#print axioms LonelyRunner.circleNorm_le_abs_sub_int
#print axioms LonelyRunner.int_band_of_circleNorm_ge
#print axioms LonelyRunner.exists_balanced_pairSum_cell_peak
#print axioms LonelyRunner.exists_pairSum_time_of_witness
#print axioms LonelyRunner.pairSumCertificate_of_witness
#print axioms LonelyRunner.exists_witness_iff_pairSumCertificate
#print axioms LonelyRunner.positiveIntegerConjecture_iff_pairSumCertificateConjecture
#print axioms LonelyRunner.conjecture_iff_pairSumCertificateConjecture
#print axioms LonelyRunner.circleNorm_mul_abs_right
#print axioms LonelyRunner.exists_stationaryWitness_abs_iff
#print axioms LonelyRunner.exists_stationaryWitness_scale_iff
#print axioms LonelyRunner.exists_stationaryWitness_natScale_iff
#print axioms LonelyRunner.clearRationalSpeed_cast
#print axioms LonelyRunner.clearRationalSpeed_injective
#print axioms LonelyRunner.positiveIntegerConjecture_iff_distinctPositiveRationalConjecture
#print axioms LonelyRunner.distinctPositiveRationalConjecture_iff_positiveRationalConjecture
#print axioms LonelyRunner.positiveIntegerConjecture_iff_positiveRationalConjecture
#print axioms LonelyRunner.mFourier_orbitHom_eq_one_iff
#print axioms LonelyRunner.integrable_add_closedSubgroup
#print axioms LonelyRunner.continuous_integral_add_closedSubgroup
#print axioms LonelyRunner.integral_mFourier_closedSubgroup_eq_zero_of_exists_ne_one
#print axioms LonelyRunner.closedSubgroupCosetSeparator_eq_one
#print axioms LonelyRunner.exists_mFourier_separating
#print axioms LonelyRunner.orbitHom_mem_orbitTopologicalClosure_of_relations
#print axioms LonelyRunner.orbitHom_mem_closure_range_of_relations
#print axioms LonelyRunner.velocity_reconstruction
#print axioms LonelyRunner.integer_relation_annihilates_row
#print axioms LonelyRunner.bhk_adjacentRatioCombination
#print axioms LonelyRunner.exists_adjacent_image_values
#print axioms LonelyRunner.bhk_collisionWitness_of_adjacentRatios
#print axioms LonelyRunner.exists_positive_rational_of_integer_relations
#print axioms LonelyRunner.exists_rationalRow_ratio_ne_of_irrational
#print axioms LonelyRunner.exists_bhk_collisionWitness_of_irrational
#print axioms LonelyRunner.exists_stationaryWitness_of_rational_collision
#print axioms LonelyRunner.positiveRationalConjecture_implies_positiveRealWitness
#print axioms LonelyRunner.positiveRationalConjecture_implies_stationaryConjecture
#print axioms LonelyRunner.stationaryConjecture_iff_positiveRationalConjecture
#print axioms LonelyRunner.conjecture_iff_positiveIntegerConjecture
#print axioms LonelyRunner.twoMovingSpeeds_of_abs_le
#print axioms LonelyRunner.twoMovingSpeeds
#print axioms LonelyRunner.twoMovingRunners
#print axioms LonelyRunner.mem_pivotCandidates_scale_reduce_iff
#print axioms LonelyRunner.mem_pivotBadResidues_scale_reduce_iff
#print axioms LonelyRunner.pivotCompleteCover_scale_iff
#print axioms LonelyRunner.coveredPivots_scale
#print axioms LonelyRunner.internalCoverRedundantAt_scale_iff
#print axioms LonelyRunner.maxCoveredDivisible_iff_unrestricted
#print axioms LonelyRunner.primitiveSpeedFamily_iff_speedGCD_eq_one
#print axioms LonelyRunner.exists_scaleSpeeds_primitive
#print axioms LonelyRunner.primitiveMaxCovered_iff_unrestricted
#print axioms LonelyRunner.primitiveMaxCovered_split_iff
#print axioms LonelyRunner.maxCoveredNondivisible_iff_primitiveNondivisible
#print axioms LonelyRunner.maxCovered_iff_primitiveDivisible_and_nondivisible

-- First Astra research pass: exact auxiliary arithmetic, not unrestricted LRC.
#print axioms LonelyRunner.normalizedBadCount_ownerKernel_bound
#print axioms LonelyRunner.pivotBadResidues_ownerKernel_bound
#print axioms LonelyRunner.affine_avoidance_of_slope_product
#print axioms LonelyRunner.affine_avoidance_card_sub_two

-- Second Astra pass: exact zero kernels and the restricted family certificate.
#print axioms LonelyRunner.mem_pivotZeroResidues
#print axioms LonelyRunner.card_range_mul_mod_eq_zero
#print axioms LonelyRunner.card_pivotZeroResidues
#print axioms LonelyRunner.pivotZeroResidues_subset_pivotBadResidues
#print axioms LonelyRunner.pivotZeroResidues_subset_of_gcd_dvd
#print axioms LonelyRunner.normalizedZeroKernel_capacity
#print axioms LonelyRunner.pivotZeroResidues_capacity
#print axioms LonelyRunner.one_and_last_mem_pivotBadResidues_sdiff_pivotZeroResidues
#print axioms LonelyRunner.exists_candidate_avoiding_kernel_family_two_or_more
#print axioms LonelyRunner.exists_candidate_avoiding_kernel_family
#print axioms LonelyRunner.exists_pivotCandidate_avoiding_ownerKernel_family
#print axioms LonelyRunner.exists_pivotCandidate_avoiding_ownerKernel_family_of_gcd_dvd
#print axioms LonelyRunner.exists_ownerKernel_circleNorm_witness
#print axioms LonelyRunner.circleNorm_ge_of_affine_grid_band
#print axioms LonelyRunner.exists_affine_grid_rounding
#print axioms LonelyRunner.nat_mod_band_of_zmod_avoidance
#print axioms LonelyRunner.affine_grid_pivot_witness
#print axioms LonelyRunner.circleNorm_ge_of_affine_grid_residue_band
#print axioms LonelyRunner.affine_avoidance_allow_zero_scale
#print axioms LonelyRunner.affine_grid_full_size_witness
#print axioms LonelyRunner.exists_affine_shift_rounding
#print axioms LonelyRunner.affine_shift_large_scalar_bounds
#print axioms LonelyRunner.affine_shift_ordinary_correction_bound
#print axioms LonelyRunner.affine_grid_one_zero_witness

-- Fourth Astra pass: explicit family, with no primality or parity restriction.
#print axioms LonelyRunner.affine_dense_family_witness

-- Fifth Astra pass: simultaneous zero rows and smaller affine families.
#print axioms LonelyRunner.affine_avoidance_card_le_sub_two
#print axioms LonelyRunner.affine_grid_multiple_zero_witness

-- Ninth Astra pass: weighted avoidance and an explicit one-outlier family.
#print axioms LonelyRunner.weighted_affine_avoidance
#print axioms LonelyRunner.weighted_affine_avoidance_author
#print axioms LonelyRunner.affine_one_outlier_family_witness_nat
#print axioms LonelyRunner.affine_one_outlier_family_witness

-- Tenth Astra pass: exact cyclic bands, including arbitrary wrapping.
#print axioms LonelyRunner.circleNorm_affine_grid_iff_modular_band

-- Eleventh Astra pass: affine cyclic bad residues and the exact complement.
#print axioms LonelyRunner.not_mem_affineCyclicBadResidues_iff
#print axioms LonelyRunner.affineCyclicBadResidues_not_mem_iff_modular_band
#print axioms LonelyRunner.circleNorm_affine_grid_iff_not_mem_bad_residues

-- Fifteenth Astra pass: exact periodic counts and denominator-seven arithmetic.
#print axioms LonelyRunner.card_filter_range_mul_mod_coprime
#print axioms LonelyRunner.card_filter_range_mod_mem
#print axioms LonelyRunner.card_filter_pivotCandidates_mod_mem
#print axioms LonelyRunner.normalizedBadCount_seven_seven
#print axioms LonelyRunner.normalizedBadCount_seven_one_bound
#print axioms LonelyRunner.normalizedBadCount_seven_seven_bound
#print axioms LonelyRunner.normalizedBadCount_seven_seven_le_two
#print axioms LonelyRunner.normalizedBadCount_seven_seven_lt_remainder_budget
#print axioms LonelyRunner.threeLowerOwner_noncover_seven
#print axioms LonelyRunner.threeLowerOwner_circleNorm_witness_seven

-- Sixteenth Astra pass: arbitrary-height denominator-nine four-owner theorem.
#print axioms LonelyRunner.fourLowerOwner_noncover_nine
#print axioms LonelyRunner.fourLowerOwner_circleNorm_witness_nine

-- These declarations retain the unproved universal Prompt95 premise.
#print axioms LonelyRunner.internalCoverRedundantAt_iff_no_internal_complete_cover
#print axioms LonelyRunner.positiveIntegerConjecture_of_maxCoveredPivotInternalCoverRedundancy
#print axioms LonelyRunner.conjecture_of_maxCoveredPivotInternalCoverRedundancy

-- Nineteenth Astra pass: transport a supplied witness with explicit margins.
#print axioms LonelyRunner.exists_nearestPivotGrid_residue

-- Sharper inclusive cutoff: the large-height theorem is stationary, while
-- normalization and induction connect the finite obligation to the conjecture.
#print axioms LonelyRunner.primitive_sorted_largeHeight_stationary_lonelyAt
#print axioms LonelyRunner.nonnegative_integer_stationary_lonelyAt_of_lower_and_sharperFiniteFamily
#print axioms LonelyRunner.positiveIntegerAtCount_of_lower_and_sharperFiniteFamily
#print axioms LonelyRunner.positiveIntegerConjecture_of_allSharperInclusivePrimitiveFiniteFamilies
#print axioms LonelyRunner.conjecture_iff_allSharperInclusivePrimitiveFiniteFamilies

-- Four-runner mixed finite endpoint certificate.
#print axioms LonelyRunner.fourRunnerMixed_finiteCoverage
#print axioms LonelyRunner.fourRunnerMixedRowOK_sound
#print axioms LonelyRunner.primitive_fourRunnerMixed_of_le_36
#print axioms LonelyRunner.fourRunnerMixed_lowerCount4
#print axioms LonelyRunner.primitive_fourRunnerMixed_of_gt_36
#print axioms LonelyRunner.primitive_fourRunnerMixed

-- Four-runner mixed classification and its strict ordinary-witness consequence.
#print axioms LonelyRunner.not_fourRunnerMixed_one_two_three
#print axioms LonelyRunner.fourRunnerMixed_of_not_exception
#print axioms LonelyRunner.fourRunnerMixed_iff
#print axioms LonelyRunner.not_strict_ordinary_one_two_three
#print axioms LonelyRunner.strict_ordinary_witness_implies_fourRunnerMixed

-- Bounded ordinary and real bridges, followed by the exact four-total-runner
-- specialization.  These do not assert any unrestricted count theorem.
#print axioms LonelyRunner.threeMovingNaturalSpeeds
#print axioms LonelyRunner.threeMovingNaturalRunners
#print axioms LonelyRunner.lowerCountPositiveIntegerHypothesis_five
#print axioms LonelyRunner.exists_stationaryStrictWitness_of_relations
#print axioms LonelyRunner.positiveRealWitness_of_lowerCount
#print axioms LonelyRunner.stationaryWitness_of_lowerCount
#print axioms LonelyRunner.lonelyAt_of_lowerCount
#print axioms LonelyRunner.fourRunners

-- Buffered insertion and sufficient five-runner classes. The two parameter
-- inequalities remain explicit; this is not a universal five-runner theorem.
#print axioms LonelyRunner.bufferedRunnerInsertion
#print axioms LonelyRunner.fiveRunnerMixed_one_two_three
#print axioms LonelyRunner.fiveRunnerMixed_exceptional
#print axioms LonelyRunner.fiveRunnerMixed_of_buffer_inequalities
#print axioms LonelyRunner.fiveRunnerMixed_of_three_mul_height_ge

-- Generic certificate interfaces preserve closed coordinatewise margins and
-- strict common margins. These are completeness/checking tools, not supply.
#print axioms LonelyRunner.rationalMargin_circleNorm_iff
#print axioms LonelyRunner.rationalMarginResidueOK_iff
#print axioms LonelyRunner.rationalMarginRowOK_iff
#print axioms LonelyRunner.rationalMarginRowOK_sound
#print axioms LonelyRunner.rationalMarginRowOK_circleNorm_iff
#print axioms LonelyRunner.rationalMarginRowOK_exists_positive_time
#print axioms LonelyRunner.exists_endpoint_time_of_witness
#print axioms LonelyRunner.exists_strictWitness_iff_pairSum
