import Mathlib.Algebra.Algebra.Rat
import Mathlib.Data.Real.Basic
import Mathlib.LinearAlgebra.Basis.Basic
import Mathlib.LinearAlgebra.Dimension.Free
import Mathlib.LinearAlgebra.FiniteDimensional.Defs

noncomputable section

open Finset
open scoped BigOperators

namespace LonelyRunner

/-- The finite-dimensional rational vector space generated by the velocities. -/
def rationalSpan {m : ℕ} (u : Fin m → ℝ) : Submodule ℚ ℝ :=
  Submodule.span ℚ (Set.range u)

instance rationalSpan.instModuleFinite {m : ℕ} (u : Fin m → ℝ) :
    Module.Finite ℚ (rationalSpan u) :=
  Module.Finite.span_of_finite ℚ (Set.finite_range u)

/-- A fixed finite basis of the rational span of the velocities. -/
def rationalBasis {m : ℕ} (u : Fin m → ℝ) :
    Module.Basis (Fin (Module.finrank ℚ (rationalSpan u))) ℚ (rationalSpan u) :=
  Module.finBasis ℚ (rationalSpan u)

/-- A velocity regarded as an element of its rational span. -/
def velocityInRationalSpan {m : ℕ} (u : Fin m → ℝ) (i : Fin m) : rationalSpan u :=
  ⟨u i, Submodule.subset_span (Set.mem_range_self i)⟩

/-- The `k`th rational coordinate row of the velocity vector. -/
def rationalRow {m : ℕ} (u : Fin m → ℝ)
    (k : Fin (Module.finrank ℚ (rationalSpan u))) (i : Fin m) : ℚ :=
  (rationalBasis u).repr (velocityInRationalSpan u i) k

theorem velocity_reconstruction {m : ℕ} (u : Fin m → ℝ) (i : Fin m) :
    u i = ∑ k, (rationalRow u k i : ℝ) * ((rationalBasis u k : rationalSpan u) : ℝ) := by
  have h := (rationalBasis u).sum_repr (velocityInRationalSpan u i)
  calc
    u i = ((velocityInRationalSpan u i : rationalSpan u) : ℝ) := rfl
    _ = ((∑ k, (rationalBasis u).repr (velocityInRationalSpan u i) k •
        (rationalBasis u k : rationalSpan u) : rationalSpan u) : ℝ) :=
      congrArg Subtype.val h.symm
    _ = ∑ k, (rationalRow u k i : ℝ) * ((rationalBasis u k : rationalSpan u) : ℝ) := by
      change (rationalSpan u).subtype
        (∑ k, (rationalBasis u).repr (velocityInRationalSpan u i) k •
          (rationalBasis u k : rationalSpan u)) = _
      rw [map_sum]
      apply Finset.sum_congr rfl
      intro k hk
      rw [map_smul]
      rfl

/-- A rational relation among the original real velocities annihilates every coordinate row. -/
theorem rational_relation_annihilates_row {m : ℕ} (u : Fin m → ℝ) (c : Fin m → ℚ)
    (h : ∑ i, (c i : ℝ) * u i = 0)
    (k : Fin (Module.finrank ℚ (rationalSpan u))) :
    ∑ i, c i * rationalRow u k i = 0 := by
  have hV : ∑ i, c i • velocityInRationalSpan u i = 0 := by
    apply Subtype.ext
    simpa [velocityInRationalSpan, Algebra.smul_def] using h
  have hk := congrArg (fun x : rationalSpan u => (rationalBasis u).repr x k) hV
  simpa [rationalRow] using hk

/-- In particular, every integer relation among the velocities annihilates every rational row. -/
theorem integer_relation_annihilates_row {m : ℕ} (u : Fin m → ℝ) (a : Fin m → ℤ)
    (h : ∑ i, (a i : ℝ) * u i = 0)
    (k : Fin (Module.finrank ℚ (rationalSpan u))) :
    ∑ i, (a i : ℚ) * rationalRow u k i = 0 := by
  apply rational_relation_annihilates_row u (fun i => (a i : ℚ))
  simpa using h

end LonelyRunner
